### ISSUE TITLE
OS X 10.11.6 Compatibility

### ISSUE THREAD

**Issue by rawdr** [positive-security/send-my#1]
Is it possible to compile the app with greater compatibility for older versions? I'm running 10.11.6 on an old iMac and when I run the OFFetchReports app it says "The application requires OS X 10.15 or later."

Thanks.

**Comment by breakingsystems** [comment]
This restriction comes from _OpenHaystack_, which _Send My_ is based on.
The _OpenHaystack_ authors have [previously declined a backport request due to resource constraints](https://github.com/seemoo-lab/openhaystack/issues/12) and it being experimental software. Recently, a [new issue was opened in their repo](https://github.com/seemoo-lab/openhaystack/issues/61) and somebody seems to be working on it, so I'd suggest you to follow this issue. 
With _Send My_ only being proof of concept software, backwards compatibility however is also not a priority of this project.

**Comment by rawdr** [comment]
I discovered this recently and have been trying to get an OSX VM working to test the software. OpenHaystack actually requires OSX 11 which is crazy, doesn't even support 10.15 which is only a couple years old.

Anyway thank you for the reply and for your work on this. Have a good one.
