### ISSUE TITLE
Why the issue sent in the repository will send to my E-mailbox?

### ISSUE THREAD

**Issue by SkyD666** [positive-security/send-my#3]
It's very strange
![QQ图片20210516183003](https://user-images.githubusercontent.com/32453770/118394015-c905e380-b674-11eb-89d2-86381dfec4f3.png)

**Comment by jtagcat** [comment]
Because somebody has replied to you. Issues are similar to mailing lists, in some sense, they _are_ replies.

When you reply, you also get subscribed to future replies.

You may opt-out per-issue with the `Unsubscribe` button, or the link in the e-mail.

To configure your notifications, see https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications

Please close the issue, as it's unrelated to the repo.

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/118394257-1eb99c00-b633-11eb-95d6-2de7d902d066.png)

You have watched the repo for all activity as well.
